# Run the following command to start the Eventmap stack:
# TICKETMASTER_API_KEY=123 docker compose up -d
# Replace "123" with your Ticketmaster API key

services:
  backend:
    image: ghcr.io/thoranilsson/eventmap/backend:latest
    container_name: eventmap-backend
    ports:
      - "5000:8080"
    environment:
      - Ticketmaster__ApiKey=${TICKETMASTER_API_KEY}

  frontend:
    image: ghcr.io/thoranilsson/eventmap/frontend:latest
    container_name: eventmap-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
